### ISSUE TITLE
Unable to access kubernetes UI from browser

### ISSUE THREAD

**Issue by likku3** [wearemakery/kubestack-aws#2]
Hi Team,

I have followed all the steps mentioned and able to create k8s cluster .Till here everything is fine when i am trying to access the master with the aws Elastic Load Balancing url I am getting certificate error(NET::ERR_CERT_AUTHORITY_INVALID) even after ignoring it displaying me as "Unauthorized".It would be great if some hints are given.

Thanks in advance.

**Comment by gyulavoros** [comment]
How do you try to access the cluster? `kubectl` gives you the error?

**Comment by likku3** [comment]
Through Kubectl it's working like  a charm but when trying to access from browser i am getting the error.

**Comment by gyulavoros** [comment]
Note, that the current setup only deploys SkyDNS as a cluster add-on, Dashboard, Monitoring, Registry and other add-ons are up to you to install. So there is not any "component" that you should be able to talk to via HTTP (browser). Kubernetes has a REST API, but that is protected by SSL and your browser doesn't set up to present the certificate, that's why you got the error, I guess. What do you want to achieve via browser?

**Comment by likku3** [comment]
I totally agree to your points that to access kubernetes UI we need dashboard add on. In required to access the below modules through browser.

Example url : https://awsdns.com/api
"/api",
    "/api/v1",
    "/apis",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"

and I suspect the same that my browser is not accepting or validating the certificate.Is there any way to over come this because in future might require to access the kubernetes API through browser.

**Comment by gyulavoros** [comment]
There are a few related issues in the kubernetes/dashboard repo:

https://github.com/kubernetes/dashboard/issues/574
https://github.com/kubernetes/dashboard/issues/374

According to these, you should be able to access the REST API via curl like:
`curl --cacert <cert> <url>`

**Comment by likku3** [comment]
but still unable to access through curl and getting the message as Unauthorised.I think it's related to Openssl CA error because it's displaying as bad signature when trying to access from chrome.

**Comment by gyulavoros** [comment]
There is an alternative approach described in http://kubernetes.io/docs/user-guide/accessing-the-cluster/ that I've just tried and works fine. You can run `kubectl` in proxy mode and talk to `localhost` to access the `apiserver`.

```
$ kubectl proxy --port=8080
$ curl http://localhost:8080/api/
{
  "versions": [
    "v1"
  ]
}
```

**Comment by likku3** [comment]
Kudos !!! gyulavoros .Thank you for the valuable information and your help,I am able to access now.
