### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by onbjerg** [wearemakery/kubestack-aws#3]
Is this production ready?

**Comment by gyulavoros** [comment]
The Terraform script follows exactly https://coreos.com/kubernetes/docs/latest/getting-started.html. There was a recent update to the guide, upgrading the documentation to Kubernetes 1.2.x, so we are planning to upgrade as well. Besides that, we use it in production.

**Comment by onbjerg** [comment]
Very cool! Thank you for the swift response
